import { ListingCardProps } from '@/components/marketplace/listing-card'

export const mockListings: ListingCardProps[] = [
  {
    id: '1',
    title: 'Habitación exterior en piso compartido',
    type: 'room',
    price: 350,
    city: 'Madrid',
    neighborhood: 'Moncloa',
    bedrooms: 3,
    bathrooms: 2,
    area: 15,
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
    featured: true,
    verified: true,
    billsIncluded: true,
    furnished: true,
    university: 'UCM',
    distance: '5 min',
  },
  {
    id: '2',
    title: 'Piso completo reformado cerca de campus',
    type: 'apartment',
    price: 1200,
    city: 'Madrid',
    neighborhood: 'Ciudad Universitaria',
    bedrooms: 2,
    bathrooms: 1,
    area: 65,
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
    verified: true,
    billsIncluded: false,
    furnished: true,
    university: 'UC3M',
    distance: '10 min',
  },
  {
    id: '3',
    title: 'Habitación doble con baño privado',
    type: 'room',
    price: 450,
    city: 'Barcelona',
    neighborhood: 'Gràcia',
    bedrooms: 2,
    bathrooms: 2,
    area: 18,
    images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'],
    featured: true,
    verified: true,
    billsIncluded: true,
    furnished: true,
    university: 'UB',
    distance: '15 min',
  },
  {
    id: '4',
    title: 'Estudio moderno para estudiante',
    type: 'studio',
    price: 650,
    city: 'Valencia',
    neighborhood: 'Benimaclet',
    bedrooms: 1,
    bathrooms: 1,
    area: 35,
    images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800'],
    verified: true,
    billsIncluded: false,
    furnished: true,
    university: 'UV',
    distance: '8 min',
  },
  {
    id: '5',
    title: 'Habitación en piso compartido con estudiantes',
    type: 'room',
    price: 280,
    city: 'Sevilla',
    neighborhood: 'Nervión',
    bedrooms: 4,
    bathrooms: 2,
    area: 12,
    images: ['https://images.unsplash.com/photo-1556912173-46c336c7fd55?w=800'],
    verified: true,
    billsIncluded: true,
    furnished: true,
    university: 'US',
    distance: '12 min',
  },
  {
    id: '6',
    title: 'Piso compartido búsqueda compañero/a',
    type: 'shared',
    price: 300,
    city: 'Madrid',
    neighborhood: 'Lavapiés',
    bedrooms: 1,
    bathrooms: 1,
    area: 14,
    images: ['https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800'],
    verified: false,
    billsIncluded: true,
    furnished: true,
    university: 'UAH',
    distance: '20 min',
  },
  {
    id: '7',
    title: 'Ático con terraza cerca de facultad',
    type: 'apartment',
    price: 950,
    city: 'Granada',
    neighborhood: 'Centro',
    bedrooms: 2,
    bathrooms: 1,
    area: 70,
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800'],
    featured: true,
    verified: true,
    billsIncluded: false,
    furnished: true,
    university: 'UGR',
    distance: '5 min',
  },
  {
    id: '8',
    title: 'Habitación luminosa en zona tranquila',
    type: 'room',
    price: 320,
    city: 'Salamanca',
    neighborhood: 'Centro',
    bedrooms: 3,
    bathrooms: 1,
    area: 16,
    images: ['https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800'],
    verified: true,
    billsIncluded: true,
    furnished: true,
    university: 'USAL',
    distance: '10 min',
  },
  {
    id: '9',
    title: 'Estudio con cocina americana',
    type: 'studio',
    price: 550,
    city: 'Zaragoza',
    neighborhood: 'Delicias',
    bedrooms: 1,
    bathrooms: 1,
    area: 40,
    images: ['https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800'],
    verified: true,
    billsIncluded: false,
    furnished: true,
    university: 'Unizar',
    distance: '7 min',
  },
  {
    id: '10',
    title: 'Habitación en piso reformado',
    type: 'room',
    price: 400,
    city: 'Bilbao',
    neighborhood: 'Deusto',
    bedrooms: 2,
    bathrooms: 1,
    area: 14,
    images: ['https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800'],
    verified: true,
    billsIncluded: true,
    furnished: true,
    university: 'Deusto',
    distance: '3 min',
  },
  {
    id: '11',
    title: 'Piso completo 3 habitaciones',
    type: 'apartment',
    price: 1400,
    city: 'Madrid',
    neighborhood: 'Chamberí',
    bedrooms: 3,
    bathrooms: 2,
    area: 85,
    images: ['https://images.unsplash.com/photo-1556912998-c71d64b2e2c1?w=800'],
    featured: true,
    verified: true,
    billsIncluded: false,
    furnished: true,
    university: 'UPM',
    distance: '15 min',
  },
  {
    id: '12',
    title: 'Habitación doble para 2 estudiantes',
    type: 'room',
    price: 250,
    city: 'Murcia',
    neighborhood: 'Centro',
    bedrooms: 2,
    bathrooms: 1,
    area: 20,
    images: ['https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=800'],
    verified: false,
    billsIncluded: true,
    furnished: true,
    university: 'UM',
    distance: '8 min',
  },
]
